name: refrigerator_management_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/
    - lib/images/
    - lib/images/recommendation/
  # fonts:
  #   # For details regarding fonts from package dependencies,
  #   # see https://flutter.dev/custom-fonts/#from-packages
  #   - family: Montserrat
  #     fonts:
  #       - asset: lib/fonts/Montserrat/Montserrat-Thin.ttf
  #         weight: 100
  #       - asset: lib/fonts/Montserrat/Montserrat-ThinItalic.ttf
  #         style: italic
  #         weight: 100
  #       - asset: lib/fonts/Montserrat/Montserrat-ExtraLight.ttf
  #         weight: 200
  #       - asset: lib/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
  #         style: italic
  #         weight: 200
  #       - asset: lib/fonts/Montserrat/Montserrat-Light.ttf
  #         weight: 300
  #       - asset: lib/fonts/Montserrat/Montserrat-LightItalic.ttf
  #         style: italic
  #         weight: 300
  #       - asset: lib/fonts/Montserrat/Montserrat-Regular.ttf
  #         weight: 400
  #       - asset: lib/fonts/Montserrat/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: lib/fonts/Montserrat/Montserrat-MediumItalic.ttf
  #         style: italic
  #         weight: 500
  #       - asset: lib/fonts/Montserrat/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
  #         style: italic
  #         weight: 600
  #       - asset: lib/fonts/Montserrat/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: lib/fonts/Montserrat/Montserrat-BoldItalic.ttf
  #         style: italic
  #         weight: 700
  #       - asset: lib/fonts/Montserrat/Montserrat-ExtraBold.ttf
  #         weight: 800
  #       - asset: lib/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
  #         style: italic
  #         weight: 800
  #       - asset: lib/fonts/Montserrat/Montserrat-Black.ttf
  #         weight: 900
  #       - asset: lib/fonts/Montserrat/Montserrat-BlackItalic.ttf
  #         style: italic
  #         weight: 900